name: Sync Upstream

permissions: write-all              # grant write permission

on:
  schedule:
    - cron: '20 4 * * *'            # scheduled for 04:20 daily
  workflow_dispatch:                # trigger manually

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: quicktype
          base: quicktype
          head: master
