name: Sync Upstream

permissions: write-all              # grant write permission

on:
  schedule:
    - cron: '20 4 * * *'            # scheduled for 04:20 daily
  workflow_dispatch:                # trigger manually

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: quicktype/quicktype
          upstream-branch: master
          branch: master
